import {
  bannerImage,
  earphones_a_1,
  earphones_a_2,
  earphones_a_3,
  earphones_a_4,
  earphones_b_1,
  earphones_b_2,
  earphones_b_3,
  earphones_b_4,
  earphones_c_1,
  earphones_c_2,
  earphones_c_3,
  earphones_c_4,
  headphones_a_1,
  headphones_a_2,
  headphones_a_3,
  headphones_a_4,
  headphones_b_1,
  headphones_b_2,
  headphones_b_3,
  headphones_b_4,
  headphones_c_1,
  headphones_c_2,
  headphones_c_3,
  headphones_c_4,
  speaker1,
  speaker2,
  speaker3,
  speaker4,
  watch_1,
  watch_2,
  watch_3,
  watch_4,
} from "./images";

export const heroBanner = {
  smallText: "Beats Solo Air",
  midText: "Summer Sale",
  largeText1: "FINE",
  image: bannerImage,
  buttonText: "Shop Now",
  desc: "Best headphones on the market",
};

export const products = [
  {
    _id: "1",
    name: "boAt Party Pal 50",
    price: "56",
    image: [speaker1, speaker2, speaker3, speaker4],
  },
  {
    _id: "2",
    name: "boAt Rockerz 451",
    price: "49",
    image: [headphones_c_1, headphones_c_2, headphones_c_3, headphones_c_4],
  },
  {
    _id: "3",
    name: "boAt Immortal 1000D",
    price: "50",
    image: [headphones_a_1, headphones_a_2, headphones_a_3, headphones_a_4],
  },
  {
    _id: "4",
    name: "boAt BassHeads 242",
    price: "34",
    image: [earphones_a_1, earphones_a_2, earphones_a_3, earphones_a_4],
  },
  {
    _id: "5",
    name: "Watch Blaze",
    price: "49",
    image: [watch_1, watch_2, watch_3, watch_4],
  },
  {
    _id: "6",
    name: "BOAT Airdopes 281 Pro",
    price: "69",
    image: [earphones_b_1, earphones_b_2, earphones_b_3, earphones_b_4],
  },
  {
    _id: "7",
    name: "BOAT BassHeads 900",
    price: "49",
    image: [headphones_b_1, headphones_b_2, headphones_b_3, headphones_b_4],
  },
  {
    _id: "8",
    name: "boAt Rockerz 333",
    price: "55",
    image: [earphones_c_1, earphones_c_2, earphones_c_3, earphones_c_4],
  },
];

export const bannderData = [
  {
    discount: "20% OFF",
    largeText1: "FINE",
    largeText2: "SMILE",
    saleTime: "15 Now to 7 Dec",
    smallText: "Beats Solo Air",
    midText: "Summer Sale",
    desc: "Best headphones on the market",
    product: "",
    buttonText: "Shop Now",
    image: headphones_c_1,
  },
];
